export const ROUTES = {
  HOME: '/',
  STOREFRONT: {
    PRODUCTS: '/products',
    PRODUCT_DETAIL: (slug: string) => `/products/${slug}`,
    CATEGORIES: (slug: string) => `/categories/${slug}`,
    CART: '/cart',
    CHECKOUT: '/checkout',
    ORDERS: '/orders',
    ORDER_DETAIL: (orderId: string) => `/orders/${orderId}`,
  },
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
  },
  CUSTOMER: {
    ACCOUNT: '/account',
    ADDRESSES: '/account/addresses',
    ORDERS: '/account/orders',
  },
  VENDOR: {
    DASHBOARD: '/vendor/dashboard',
    PRODUCTS: '/vendor/products',
    NEW_PRODUCT: '/vendor/products/new',
    PRODUCT_DETAIL: (productId: string) => `/vendor/products/${productId}`,
    INVENTORY: '/vendor/inventory',
    ORDERS: '/vendor/orders',
    ORDER_DETAIL: (orderId: string) => `/vendor/orders/${orderId}`,
  },
  API: {
    HEALTH: '/api/v1/health',
    AUTH: '/api/v1/auth',
    CUSTOMERS: '/api/v1/customers',
    VENDORS: '/api/v1/vendors',
    PRODUCTS: '/api/v1/products',
    CATEGORIES: '/api/v1/categories',
    INVENTORY: '/api/v1/inventory',
    CART: '/api/v1/cart',
    CHECKOUT: '/api/v1/checkout',
    ORDERS: '/api/v1/orders',
    PAYMENTS: '/api/v1/payments',
    SHIPMENTS: '/api/v1/shipments',
    NOTIFICATIONS: '/api/v1/notifications',
  },
} as const;
